dependencies:
  build:
   - maven:3.5.4
   - java:11.0.8

build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04-nonroot
    commands:
      - mvn verify -Pjava-bdb.1-0 -DskipITs=false

ci:
  builds:
    - name: default
      build_target: default
